### ISSUE TITLE
Initialisierung

### ISSUE THREAD

**Issue by polkehn** [MChrista/Studienarbeit#2]
_Basierend auf Hr. Reutemanns E-mail_

### Text ###
Wie oben bereits beschrieben, sollte das Page Directory nicht hier initialisiert werden, sondern in einer Initialisierungsfunktion, z.B. init_paging().

### ToDo ###
- Auslagern der Intialisierungsfunktion

**Comment by MChrista** [comment]
Ist erledigt.
In der Init Funktion wird der Kernel in die Kernel_Page_Table 1:1 gemappt.
Zusätzlich werden statisch zwei weitere Page_Tables angelegt.
