### ISSUE TITLE
Sinnvolle Testfälle finden

### ISSUE THREAD

**Issue by polkehn** [MChrista/Studienarbeit#4]
_Basierend auf Hr. Reutemanns E-mail_

### Text ###
4. - main(): Adressbereich der Testfälle
Die Testfälle passen nicht zu einen 32-bit Linuxprogramm, welches typischerweise mit der Adresse 0x08048000 startet. Weitere Adressen die auftreten können und die durch Testfälle abgedeckt werden sollten, sind Zugriffe auf den Stack sowie Speicherzugriffe des Kernels innerhalb dessen Bereich. Das führt zum nächsten Punkt bzgl. Kerneladressen…

5. - allgemein
Der Adressbereich für den Kernel (die unteren 1 MB) sollen durch das Paging 1:1, d.h. virtuelle Adresse x entspricht der gleichen physikalischen Adresse, in den physikalischen Speicherbereich abgebildet werden. Für diese Zuordnung reicht eine Page Table, die aber nur dem Kernel zugewiesen ist. Dies ist in Ihrem Programm noch nicht berücksichtigt. Die Zuordnung der Pages soll statisch bei der Initialisierung erfolgen.

### ToDo ###
- Interessante Adressen für Testfälle sammeln
- Testfälle in automatischen Tests abbilden
- Testfälle für 1:1 Mapping im Kerneladressbereich in tests abbilden
- Programm entsprechend anpassen

**Comment by MChrista** [comment]
1:1 Mapping ist in init_paging() realisiert.

**Comment by polkehn** [comment]
Testfälle aus der E-mail in input datei (/paging/input) übernommen. Wird vom programm gelesen.
