### ISSUE TITLE
Page Fault Handler

### ISSUE THREAD

**Issue by polkehn** [MChrista/Studienarbeit#5]
_Basierend auf Hr. Reutemanns E-mail_

### Text ###
7. - convertVirtualToPhysical: Bedingung für einen Page Fault
Die Funktion überprüft lediglich, ob für einen berechneten Page Dir Offset eine Page Table im Page Directory vorhanden ist. Eine gültige Page muss aber im entsprechenden Eintrag (page_table_offset) in der Page Table referenziert werden.

8. - pageFault(): Page Table anlegen
Bei jedem Page Fault wird eine neue Page Table erzeugt, was falsch ist (siehe 7). Die Adresse der neuen Page Table wird im entsprechenden Eintrag im Page Directory gespeichert. Da die Page Table allerdings auf dem Stack angelegt wird, ist diese Adresse nicht mehr gültig nachdem die Funktion pageFault() verlassen wurde.

### ToDo ###
- Konzept für Umgang mit Page Faults
- Implementierung

**Comment by MChrista** [comment]
Ist erledigt.
