### ISSUE TITLE
Pages zuweisen

### ISSUE THREAD

**Issue by devkjp** [MChrista/Studienarbeit#6]
_Basierend auf Hr. Reutemanns E-mail_
### Text
1. \- pageFault(): Page zuweisen
   Zeile 44 (malloc) bezieht sich vermutlich auf Ihre Frage, wie Speicherblöcke allokiert werden können. Sie verwenden dazu malloc(). Hier sollten Sie stattdessen aus einem Pool freier Pages eine zuweisen. In Ihrem Programm ist es dabei nicht erforderlich, auch tatsächlich Speicher zuzuordnen, sondern es kommt nur darauf an, dass gezeigt wird, wie die Adresse einer freien Page ermittelt und diese Page in einer Datenstruktur reserviert wird. Die Annahme ist hierbei, dass freie Pages aus dem Speicherbereich ab 1 MB, d.h. “oberhalb” des Kernels, zugeordnet werden sollen. Die Startadressen dieses Bereichs sowie die Anzahl der zur Verfügung stehenden Pages sollte im Quellcode konfigurierbar sein. Das Programm sollte außerdem den Status/Inhalt der Datenstruktur zur Verwaltung der freien Pages darstellen können. 
### ToDo
- Wie werden Pages als 'zugewiesen' markiert
- Implementierung

**Comment by MChrista** [comment]
Pagefault ist implementiert.
Optimierung, um ein Bitfeld zu implementieren ist in Arbeit.
